. ~/Development/dotfiles.local/bash/colors
. ~/Development/dotfiles.local/bash/prompt
. ~/Development/dotfiles.local/bash/env
. ~/Development/dotfiles.local/bash/aliases
. ~/Development/dotfiles.local/bash/completion/sheet
. ~/Development/dotfiles.local/bash/hitch
. ~/Development/dotfiles.local/bash/brew
. ~/Development/dotfiles.local/bash/heroku
. ~/Development/dotfiles.local/bash/erlang
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash
