#!/usr/bin/env zsh

# Install and run vim-plug

if [ ! -e "$HOME"/.vim/autoload/plug.vim ]; then
  curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

echo "Install Vim Plugins..."

# Use `xargs -o` to fix: "Vim: Warning: Input is not from a terminal"
echo "${HOME}/.vimrc.bundles +PlugInstall +PlugClean! +qa" | xargs -o vim -u
