#!/usr/bin/env zsh

append_to_zshrc() {
    local text="$1" zshrc
    local skip_new_line="${2:-0}"

    if ((0)); then # [ -w "$HOME/.zshrc.local" ]
        zshrc="$HOME/.zshrc.local"
    else
        zshrc="$HOME/.zshrc"
    fi

    if ! grep -Fqs "$text" "$zshrc"; then
        if [ "$skip_new_line" -eq 1 ]; then
            printf "%s\\n" "$text" >>"$zshrc"
        else
            printf "\\n%s\\n" "$text" >>"$zshrc"
        fi
    fi
}

# Create required dirs

mkdir $HOME/.cache
mkdir -p $HOME/.local/share
mkdir -p $HOME/.local/state

# Install and run vim-plug

if [ ! -e $HOME/.vim/autoload/plug.vim ]; then
    curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

echo "Install/update Vim Plugins..."

# Use `xargs -o` to fix: "Vim: Warning: Input is not from a terminal"
echo "${HOME}/.vimrc.bundles +PlugInstall +PlugClean! +qa" | xargs -o vim -u

if [ ! -e $HOME/.tmux/plugins/tpm ]; then
    echo "Install Tmux Plugin Manager (TPM)..."
    mkdir -p $HOME/.tmux/plugins
    git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
fi

ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export NJH_CONFIG_SECRETS="$XDG_CONFIG_HOME/secrets"

append_to_zshrc 'source $ZDOTDIR/main'

if [ ! -e $NJH_CONFIG_SECRETS/shrc ]; then
    mkdir -p $NJH_CONFIG_SECRETS
    touch $NJH_CONFIG_SECRETS/shrc
fi

if [ ! -e $NJH_CONFIG_SECRETS/gitconfig ]; then
    op read op://Setup/gitconfig/notesPlain >$NJH_CONFIG_SECRETS/gitconfig
fi
