ack:
  repo: git://github.com/mileszs/ack.vim.git
  path: bundle

tcomment:
  repo: git://github.com/tomtom/tcomment_vim.git
  path: bundle

vim-cucumber:
  repo: git://github.com/tpope/vim-cucumber.git
  path: bundle

vim-endwise:
  repo: git://github.com/tpope/vim-endwise.git
  path: bundle

vim-fugitive:
  repo: git://github.com/tpope/vim-fugitive.git
  path: vim-fugitive

vim-haml:
  repo: git://github.com/tpope/vim-haml.git
  path: bundle

vim-git:
  repo: git://github.com/tpope/vim-fugitive.git
  path: bundle

vim-ragtag:
  repo: git://github.com/tpope/vim-ragtag.git
  path: bundle

vim-snipmate:
  repo: git://github.com/msanders/snipmate.vim.git
  path: bundle

vim-surrond:
  repo: git://github.com/tpope/vim-surround.git
  path: bundle

vim-rooter:
  repo: git://github.com/airblade/vim-rooter.git
  path: bundle

vim-makegreen:
  repo: git://github.com/reinh/vim-makegreen.git
  path: bundle

vim-rails:
  repo: git://github.com/tpope/vim-rails.git
  path: bundle
