ack:
  repo: git://github.com/mileszs/ack.vim.git
  path: bundle

tcomment:
  repo: git://github.com/tomtom/tcomment_vim.git
  path: bundle

vim-snipmate:
  repo: git://github.com/msanders/snipmate.vim.git
  path: bundle

vim-rooter:
  repo: git://github.com/airblade/vim-rooter.git
  path: bundle

vim-makegreen:
  repo: git://github.com/reinh/vim-makegreen.git
  path: bundle

vim-rails:
  repo: git://github.com/tpope/vim-rails.git
  path: bundle
