ack:
  # Vim plugin for the Perl module / CLI script 'ack'
  repo: git://github.com/mileszs/ack.vim.git
  path: bundle

ctrlp.vim:
  # Fuzzy file, buffer, mru, tag, etc finder
  repo:  git://github.com/kien/ctrlp.vim.git
  path: bundle

match-it:
  # Allows you to configure % to match more than just single characters
  repo: git://github.com/tsaleh/vim-matchit.git
  path: bundle

tcomment:
  # An extensible & universal comment vim-plugin that also handles embedded filetypes
  repo: git://github.com/tomtom/tcomment_vim.git
  path: bundle

tslime.vim:
  # Send command from vim to a running tmux session
  repo: git://github.com/jgdavey/tslime.vim.git
  path: bundle

tabular:
  # Vim script for text filtering and alignment
  repo: git://github.com/godlygeek/tabular.git
  path: plugin

vim-bundler:
  # Lightweight support for Ruby's Bundler
  repo: git://github.com/tpope/vim-bundler.git
  path: bundle

vim-clojure:
  # A filetype, syntax and indent plugin for Clojure
  repo: git://github.com/vim-scripts/VimClojure.git
  path: bundle

vim-coffee-script:
  # CoffeeScript support for vim
  repo: git://github.com/kchmck/vim-coffee-script.git
  path: bundle

vim-cucumber:
  # Vim Cucumber runtime files
  repo: git://github.com/tpope/vim-cucumber.git
  path: bundle

vim-elixir:
  repo: git@github.com:elixir-lang/vim-elixir.git
  path: bundle

vim-endwise:
  # Wisely add "end" in ruby, endfunction/endif/more in vim script
  repo: git://github.com/tpope/vim-endwise.git
  path: bundle

vim-fugitive:
  # Git wrapper so awesome, it should be illegal
  repo: git://github.com/tpope/vim-fugitive.git
  path: bundle

vim-haml:
  # Vim runtime files for Haml, Sass, and SCSS
  repo: git://github.com/tpope/vim-haml.git
  path: bundle

vim-gitgutter:
  # A Vim plugin which shows a git diff in the gutter
  repo: git://github.com/airblade/vim-gitgutter.git
  path: bundle

vim-markdown:
  # Vim Markdown runtime files
  repo: git://github.com/tpope/vim-markdown.git
  path: bundle

vim-ragtag:
  # Ghetto HTML/XML mappings
  repo: git://github.com/tpope/vim-ragtag.git
  path: bundle

vim-snipmate:
  # Aims to be a concise vim script that implements some of TextMate's snippets features in Vim
  repo: git://github.com/msanders/snipmate.vim.git
  path: bundle

vim-colors-solarized:
  repo: git://github.com/altercation/vim-colors-solarized.git
  path: bundle

vim-smartinput:
  # Punctuation pairs closed for you automatically
  repo: git://github.com/kana/vim-smartinput.git
  path: bundle

vim-surrond:
  # Quoting/parenthesizing made simple
  repo: git://github.com/tpope/vim-surround.git
  path: bundle

vim-rooter:
  # Changes Vim working directory to project root
  repo: git://github.com/airblade/vim-rooter.git
  path: bundle

vim-rails:
  # Ruby on Rails power tools
  repo: git://github.com/tpope/vim-rails.git
  path: bundle

vim-repeat:
  # Enable repeating supported plugin maps with "."
  repo: git://github.com/tpope/vim-repeat.git
  path: bundle

vim-rubocop:
  repo: git@github.com:ngmy/vim-rubocop.git
  path: bundle

vim-ruby:
  repo: git@github.com:vim-ruby/vim-ruby.git
  path: bundle

vim-ruby-refactoring:
  # Refactoring tool for Ruby
  repo: git://github.com/ecomba/vim-ruby-refactoring.git
  path: bundle

vim-unimpaired:
  # Pairs of handy bracket mappings
  repo: git://github.com/tpope/vim-unimpaired.git
  path: bundle

vim-turbux:
  # Turbo Ruby testing with tmux
  repo: git://github.com/jgdavey/vim-turbux.git
  path: bundle

vim-vinegar:
  # Nice enhancements to Netrw
  repo: git://github.com/tpope/vim-vinegar.git
  path: bundle

vim-vitality:
  # Make Vim play nicely with iTerm 2 and tmux.
  repo: git://github.com/sjl/vitality.vim.git
  path: bundle

vim-ruby-xmpfilter:
  repo: git://github.com/t9md/vim-ruby-xmpfilter.git
  path: bundle
