#!/bin/sh
# https://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
# Uses config in $HOME/.ctags
# vim-fugitive will use `.git/tags` instead of `./tags`
ctags -f.git/tags.$$
mv .git/tags.$$ .git/tags
